on:
  pull_request:
  push:
    branches:
      - main
name: Test
jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        go-version: [ '1.18', '1.19']
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true
    - run: go mod verify
    - run: go build -v ./...
    - run: go vet ./...
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - name: Run staticcheck
      run: staticcheck ./...
    - run: make integration-test
      env:
        API_BASE: ${{ secrets.API_BASE }}
        TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        SMARTPAY_SECRET_KEY: ${{ secrets.SMARTPAY_SECRET_KEY }}
        SMARTPAY_PUBLIC_KEY: ${{ secrets.SMARTPAY_PUBLIC_KEY }}
        SMARTPAY_API_PREFIX: ${{ secrets.SMARTPAY_API_PREFIX }}
